export const PATH_DEFAULT = "/"
export const PATH_AUTH_LOGIN = "/sign-in"
export const PATH_AUTH_REGISTER = "/sign-up"
export const PATH_DASHBOARD = "/dashboard"
export const PATH_ADMIN = "/admin"
export const PATH_UNAUTH = "/unauthorized"
