version: '3.1'

services:
  s_pdb:
    container_name: c_pdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nakres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - D:/docker/volumes/postgre:/var/lib/postgresql/data/pgdata

  s_pgadmin:
    container_name: c_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
